services:
    nginx:
        container_name: nginx
        image: nginx:alpine  # Use the Nginx image
        ports:
            - "8080:80"  # Map port 8080 on the host to port 80 inside the container
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
            - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
        depends_on:
            - app  # Ensure PHP-FPM is started before Nginx
        networks:
            - rent_app  # Connect to the custom network

    app:
        container_name: app
        build: .  # Build from the Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
        networks:
            - rent_app  # Connect to the custom network

    db:
        container_name: rent_app_db
        image: mysql:8  # Use MySQL image
        restart: always
        ports:
            - "33061:3306"
        environment:
            MYSQL_DATABASE: rent_app  # Create a database named 'laravel'
            MYSQL_ROOT_PASSWORD: root  # Set the root password for MySQL
        volumes:
            - rent_app_db:/var/lib/mysql  # Persist MySQL data
        networks:
            - rent_app  # Connect to the custom network

    node:
        container_name: node
        image: node:20
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - rent_app
        command: bash -c "npm install && npm run build"

# Define the custom network
networks:
    rent_app:  # Create a custom network named 'rent_app'
        driver: bridge

# Define the volume for MySQL data persistence
volumes:
    rent_app_db:
